version: '3'
services:
  cart-api:
    image: ajaycheke96/cart-api
    container_name: cart-api
    ports:
      - "8080:8080"
    build: 
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysqllink
