version: '2'
services:
  mysql-link:
    image: mysql:5.7
    container_name: mysql-link
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=masterdb
      - MYSQL_USER=diamond
      - MYSQL_PASSWORD=da123
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"
  spring-app:
    image: spring-app
    container_name: spring-app
    ports:
      - "8080:8080"
    build: 
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-link
