# For Spring Boot
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-controller
  labels:
    app: cart-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-api
  template:
    metadata:
      labels:
        app: cart-api
    spec:
      containers:
      - name: cart-api
        image: ajaycheke96/cart-api:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cart-api
  labels:
    app: cart-api
spec:
  ports:
  - nodePort: 30169
    port: 8080
    targetPort: 8080
  selector:
    app: cart-api
  type: NodePort