spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
  liquibase:
      enabled: false

multitenancy:
  master:
    datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://65.0.106.67:3306/masterdb?allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: root
