spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
  liquibase:
      enabled: false

multitenancy:
  master:
    datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://0.0.0.0:3307/masterdb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      username: root
      password: root