spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
  liquibase:
      enabled: false

multitenancy:
  master:
    datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
      username: ${DB_USER}
      password: ${DB_PASSWORD}
